
SELECT
	AC_AR_DIM.AC_AR_DIM_ID					AC_AR_DIM_ID
	,CST_DIM.CST_DIM_ID						CST_DIM_ID
	,LOAN_PPS_DIM.LOAN_PPS_DIM_ID			LOAN_PPS_DIM_ID
	,PD_DIM.PD_DIM_ID						PD_DIM_ID
	,RLTNP_OFCR.EMPE_DIM_ID					RLTNP_OFCR_DIM_ID
	,IDY_DIM.IDY_DIM_ID						IDY_DIM_ID
	,LDGR_ACG_DIM.LDGR_ACG_DIM_ID			LDGR_ACG_DIM_ID
	,TERM_DIM.GRP_DIM_ID					TERM_DIM_ID
	,ADJ_OU.OU_DIM_ID						ADJ_OU_DIM_ID
	,ADJ_CCY.CCY_DIM_ID						ADJ_CCY_DIM_ID
	,ADJ_LOB.LOB_DIM_ID						ADJ_LOB_DIM_ID
	,CST_FNC_ST_DIM.FNC_ST_DIM_ID			CST_FNC_ST_DIM_ID
	,ADJ_FNC_ST_DIM.FNC_ST_DIM_ID			ADJ_FNC_ST_DIM_ID
	,MIS_ADJ_FNC_ST_DIM.FNC_ST_DIM_ID		MIS_ADJ_FNC_ST_DIM_ID
	,FNL_FNC_ST_DIM.FNC_ST_DIM_ID			FNL_FNC_ST_DIM_ID
	,FNC_ST_TP_DIM.GRP_DIM_ID				FNC_ST_TP_DIM_ID
	,CG_SEGMENT_DIM.CG_SEG_DIM_ID			CG_SEG_DIM_ID
	,MSEG_DIM.MSEG_DIM_ID					MSEG_DIM_ID
	,T.CLS_BAL_FCY
	,T.CLS_BAL_LCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'IW')
				THEN T.CLS_BAL_FCY
		ELSE nvl(lst.CLS_BAL_WTD_FCY, 0) + T.CLS_BAL_FCY
	END													CLS_BAL_WTD_FCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'IW')
				THEN T.CLS_BAL_LCY
		ELSE nvl(lst.CLS_BAL_WTD_LCY, 0) + T.CLS_BAL_LCY
	END 												CLS_BAL_WTD_LCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN T.CLS_BAL_FCY
		ELSE nvl(lst.CLS_BAL_MTD_FCY, 0) + T.CLS_BAL_FCY
	END 												CLS_BAL_MTD_FCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN T.CLS_BAL_LCY
		ELSE nvl(lst.CLS_BAL_MTD_LCY, 0) + T.CLS_BAL_LCY
	END 												CLS_BAL_MTD_LCY
	,T.LQD_AMT_FCY
	,T.LQD_AMT_LCY
	,T.DSBR_AMT_FCY
	,T.DSBR_AMT_LCY
	--ADD NEW
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN T.DSBR_AMT_LCY
		ELSE nvl(lst.DSBR_AMT_MTD_LCY, 0) + T.DSBR_AMT_LCY
	END 									DSBR_AMT_MTD_LCY
	,T.PREPYMT_AMT_FCY
	,T.PREPYMT_AMT_LCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN T.PREPYMT_AMT_FCY
		ELSE nvl(lst.PREPYMT_AMT_MTD_FCY, 0) + T.PREPYMT_AMT_FCY
	END 												PREPYMT_AMT_MTD_FCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN T.PREPYMT_AMT_LCY
		ELSE nvl(lst.PREPYMT_AMT_MTD_LCY, 0) + T.PREPYMT_AMT_LCY
	END     											PREPYMT_AMT_MTD_LCY
	,													T.PY_OFF_BFR_DUE_DT_F
	,													T.INT_RATE
	,20231231											CDR_DT_DIM_ID
	,decode(T.MUD, 'OD', 0, AC_AR_DIM.TERM_IN_MO)		TERM_IN_MO
	,SRO_DIM.SRO_DIM_ID									SRO_DIM_ID
	,T.PB_MISCODE_F
	,T.PB_CST_F
	,PYMTC_DIM.PYMTC_DIM_ID								PYMTC_DIM_ID
	,T.MUD
	,LOB.LOB_DIM_ID										LOB_DIM_ID
	,OU.OU_DIM_ID										OU_DIM_ID
	,CIC_FNC_ST_DIM.FNC_ST_DIM_ID						CIC_FNC_ST_DIM_ID
	,CCY.CCY_DIM_ID										CCY_DIM_ID
	,FNC_SVC_MINI.FNC_SVC_AR_MINI_DIM_ID				FNC_SVC_AR_MINI_DIM_ID
	,OVRL_CST.FNC_ST_DIM_ID								OVRL_CST_FNC_ST_DIM_ID
	,OVRL_MIS_ADJ.FNC_ST_DIM_ID							OVRL_MIS_ADJ_FNC_ST_DIM_ID
	,OVRL_FNL.FNC_ST_DIM_ID								OVRL_FNL_FNC_ST_DIM_ID
	,T.ORIG_CLS_BAL_FCY
	,T.ORIG_CLS_BAL_LCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN T.ORIG_CLS_BAL_FCY
		ELSE nvl(lst.ORIG_CLS_BAL_MTD_FCY, 0) + T.ORIG_CLS_BAL_FCY
	END 												ORIG_CLS_BAL_MTD_FCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN T.ORIG_CLS_BAL_LCY
		ELSE nvl(lst.ORIG_CLS_BAL_MTD_LCY, 0) + T.ORIG_CLS_BAL_LCY
	END 												ORIG_CLS_BAL_MTD_LCY
	,PD_DIM.PD_CODE||FNC_SVC_MINI.DTL_PD_CODE			CMB_PD_CODE
	--ADD
	,ORIG_PD.PD_DIM_ID									ORIG_PD_DIM_ID
	,MID1_OU.OU_DIM_ID									MIS1_OU_DIM_ID
	,NVL(PD_DTL.PD_DTL_GRP_DIM_ID, PD_DTL1.PD_DTL_GRP_DIM_ID)	PD_DTL_GRP_DIM_ID
-- Add new luc.luu
                ,T.FEE_INCM_LCY
                ,T.TOT_LMT_AMT
               -- , CASE WHEN AC_AR_DIM.AC_AR_TP = 'OD' THEN TO_DATE(20231231,'YYYYMMDD') - AC_AR_DIM.AR_END_DT 
               -- 	ELSE TO_DATE(20231231,'YYYYMMDD') - TO_DATE(T.MAX_DAY_PAST_DUE,'YYYYMMDD') END NOD_PAST_DUE
                ,T.NOD_PAST_DUE
                ,T.PNP_ARS TOT_PAST_DUE_PNP
                ,T.INT_ARS TOT_PAST_DUE_INT
                ,T.CLS_UTLZ_AMT_FCY
                ,T.PNP_DUE_AMT
                ,T.INT_DUE_AMT
                ,T.DLQ_CNT
,T.TOT_DSBR_AMT_FCY
,AC_AR_MINI.AC_AR_MINI_DIM_ID
,T.TOT_AVL_LMT_AMT
,T.INTERIM_INT
,ORIG_OU.OU_DIM_ID ORIG_OU_DIM_ID
,CST_SEG_MINI_DIM.CST_SEG_MINI_DIM_ID
FROM TWT_FNC_SVC_AR_ANL_FCT_FA T
INNER JOIN AC_AR_DIM 					ON AC_AR_DIM.AC_AR_ID = T.AC_AR_ID AND AC_AR_DIM.EFF_DT <= 20231231 AND AC_AR_DIM.END_DT > 20231231
LEFT JOIN TWT_FCA_ANL_FCT_FA_LST_DY LST ON AC_AR_DIM.AC_AR_ID = LST.AC_AR_ID AND LST.CDR_DT_DIM_ID = to_number(to_char(to_date(20231231, 'yyyymmdd')-1, 'yyyymmdd'))
LEFT JOIN FNC_SVC_AR_MINI_DIM FNC_SVC_MINI	ON FNC_SVC_MINI.FNC_SVC_AR_ID = T.AC_AR_ID AND FNC_SVC_MINI.EFF_DT <= 20231231 AND FNC_SVC_MINI.END_DT > 20231231
--add 20220311
LEFT JOIN TWT_FNC_SVC_AR_FCT_FA_CST_PD PD_CST ON T.AC_AR_ID = PD_CST.AC_AR_ID --AND T.PD_CODE = PD_CST.PD_CODE 
LEFT JOIN TWT_PUB_AC_AR_INFO TB_IF ON TB_IF.AR_ID = T.AC_AR_ID
LEFT JOIN AC_AR_MINI_DIM AC_AR_MINI ON AC_AR_MINI.EFF_DT<=20231231 AND AC_AR_MINI.END_DT>20231231
	AND NVL(PD_CST.GL_FNC_ST_CODE, 'NULL') = AC_AR_MINI.AR_FNC_ST
	AND NVL(PD_CST.CST_PD_FNC_ST_CODE, 'NULL') = AC_AR_MINI.CST_PD_FNC_ST_CODE
	AND nvl(TB_IF.CST_INCM_F,'N') = AC_AR_MINI.CST_INCM_F
--END ADD
LEFT JOIN CST_DIM 						ON CST_DIM.CST_ID = T.CST_ID AND CST_DIM.EFF_DT <= 20231231 AND CST_DIM.END_DT > 20231231
LEFT JOIN LOAN_PPS_DIM 					ON LOAN_PPS_DIM.PPS_CODE = T.LOAN_PPS_CODE AND LOAN_PPS_DIM.EFF_DT <= 20231231 AND LOAN_PPS_DIM.END_DT > 20231231 AND LOAN_PPS_DIM.PPS_TP = 'MUC DICH VAY'
LEFT JOIN PD_DIM 						ON PD_DIM.PD_CODE = T.PD_CODE AND PD_DIM.EFF_DT <= 20231231 AND PD_DIM.END_DT > 20231231
										AND CASE WHEN T.MUD IN ('LN', 'OD') THEN 'FCC' ELSE 'SMV' END = SUBSTR(PD_DIM.SRC_STM_CODE, 1, INSTR(PD_DIM.SRC_STM_CODE, '.')-1)
LEFT JOIN PD_DIM ORIG_PD 				ON ORIG_PD.PD_CODE = T.ORIG_PD_CODE AND ORIG_PD.EFF_DT <= 20231231 AND ORIG_PD.END_DT > 20231231
										AND CASE WHEN T.MUD IN ('LN', 'OD') THEN 'FCC' ELSE 'SMV' END = SUBSTR(ORIG_PD.SRC_STM_CODE, 1, INSTR(ORIG_PD.SRC_STM_CODE, '.')-1)
LEFT JOIN EMPE_DIM RLTNP_OFCR 			ON RLTNP_OFCR.EMPE_ID = T.RLTNP_OFCR_ID AND RLTNP_OFCR.EFF_DT <= 20231231 AND RLTNP_OFCR.END_DT > 20231231
LEFT JOIN IDY_DIM 						ON IDY_DIM.IDY_SHRT_CODE = T.IDY_CODE AND IDY_DIM.EFF_DT <= 20231231 AND IDY_DIM.END_DT > 20231231 AND SUBSTR(IDY_DIM.IDY_CODE, 1, INSTR(IDY_DIM.IDY_CODE, '.')-1) = 'NGANH_NGHE_KINH_TE_SBV'
LEFT JOIN LDGR_ACG_DIM 					ON LDGR_ACG_DIM.LDGR_ACG_ID = T.LDGR_ACG_ID AND LDGR_ACG_DIM.EFF_DT <= 20231231 AND LDGR_ACG_DIM.END_DT > 20231231
LEFT JOIN GRP_DIM TERM_DIM				ON TERM_DIM.GRP_CODE = decode(T.MUD, 'OD', 'S', CASE WHEN AC_AR_DIM.TERM_IN_MO <= 12 THEN 'S' WHEN AC_AR_DIM.TERM_IN_MO <= 60 THEN 'M' ELSE 'L' END)
										AND TERM_DIM.PRN_GRP_CODE = 'TERM_SEG_TP' AND TERM_DIM.EFF_DT <= 20231231 AND TERM_DIM.END_DT > 20231231
LEFT JOIN OU_DIM ADJ_OU 				ON ADJ_OU.CODE = T.ADJ_OU_CODE AND ADJ_OU.EFF_DT <= 20231231 AND ADJ_OU.END_DT > 20231231
LEFT JOIN OU_DIM OU						ON OU.CODE = T.OU_CODE AND OU.EFF_DT <= 20231231 AND OU.END_DT > 20231231
LEFT JOIN OU_DIM MID1_OU				ON MID1_OU.CODE = T.MIS1_OU_CODE AND MID1_OU.EFF_DT <= 20231231 AND MID1_OU.END_DT > 20231231
LEFT JOIN CCY_DIM ADJ_CCY 				ON ADJ_CCY.ALPB_CCY_CODE = T.ADJ_CCY_CODE AND ADJ_CCY.EFF_DT <= 20231231 AND ADJ_CCY.END_DT > 20231231
LEFT JOIN CCY_DIM CCY 					ON CCY.ALPB_CCY_CODE = T.CCY_CODE AND CCY.EFF_DT <= 20231231 AND CCY.END_DT > 20231231
LEFT JOIN LOB_DIM ADJ_LOB				ON ADJ_LOB.LOB_CODE = T.ADJ_LOB_CODE
LEFT JOIN LOB_DIM LOB					ON LOB.LOB_CODE = T.LOB_CODE
--add 20200605
LEFT JOIN PD_DTL_GRP_DIM PD_DTL			ON PD_DTL.LINE = ADJ_LOB.LOB_CODE AND PD_DTL.MAP_SPCT = PD_DIM.PD_CODE||FNC_SVC_MINI.DTL_PD_CODE
										AND PD_DTL.EFF_DT <= 20231231 AND PD_DTL.END_DT > 20231231
LEFT JOIN PD_DTL_GRP_DIM PD_DTL1			ON PD_DTL1.LINE = ADJ_LOB.LOB_CODE AND PD_DTL1.MAP_SPCT = ORIG_PD.PD_CODE
										AND PD_DTL1.EFF_DT <= 20231231 AND PD_DTL1.END_DT > 20231231
--END ADD
LEFT JOIN FNC_ST_DIM ADJ_FNC_ST_DIM 	ON ADJ_FNC_ST_DIM.FNC_ST_CODE = T.ADJ_FNC_ST_CODE AND ADJ_FNC_ST_DIM.EFF_DT <= 20231231 AND ADJ_FNC_ST_DIM.END_DT > 20231231
LEFT JOIN FNC_ST_DIM CST_FNC_ST_DIM 	ON CST_FNC_ST_DIM.FNC_ST_CODE = T.CST_FNC_ST_CODE AND CST_FNC_ST_DIM.EFF_DT <= 20231231 AND CST_FNC_ST_DIM.END_DT > 20231231
LEFT JOIN FNC_ST_DIM MIS_ADJ_FNC_ST_DIM ON MIS_ADJ_FNC_ST_DIM.FNC_ST_CODE = T.MIS_ADJ_FNC_ST_CODE AND MIS_ADJ_FNC_ST_DIM.EFF_DT <= 20231231 AND MIS_ADJ_FNC_ST_DIM.END_DT > 20231231
LEFT JOIN FNC_ST_DIM FNL_FNC_ST_DIM 	ON FNL_FNC_ST_DIM.FNC_ST_CODE = T.FNL_FNC_ST_CODE AND FNL_FNC_ST_DIM.EFF_DT <= 20231231 AND FNL_FNC_ST_DIM.END_DT > 20231231
LEFT JOIN FNC_ST_DIM OVRL_CST 			ON OVRL_CST.FNC_ST_CODE = T.OVRL_CST_FNC_ST_CODE AND OVRL_CST.EFF_DT <= 20231231 AND OVRL_CST.END_DT > 20231231
LEFT JOIN FNC_ST_DIM OVRL_MIS_ADJ 		ON OVRL_MIS_ADJ.FNC_ST_CODE = T.OVRL_MIS_ADJ_FNC_ST_CODE AND OVRL_MIS_ADJ.EFF_DT <= 20231231 AND OVRL_MIS_ADJ.END_DT > 20231231
LEFT JOIN FNC_ST_DIM OVRL_FNL 			ON OVRL_FNL.FNC_ST_CODE = T.OVRL_FNL_FNC_ST_CODE AND OVRL_FNL.EFF_DT <= 20231231 AND OVRL_FNL.END_DT > 20231231
LEFT JOIN FNC_ST_DIM CIC_FNC_ST_DIM 	ON CIC_FNC_ST_DIM.FNC_ST_CODE = T.CIC_FNC_ST_CODE AND CIC_FNC_ST_DIM.EFF_DT <= 20231231 AND CIC_FNC_ST_DIM.END_DT > 20231231
LEFT JOIN GRP_DIM FNC_ST_TP_DIM 		ON FNC_ST_TP_DIM.GRP_CODE = T.FNC_ST_TP_CODE AND FNC_ST_TP_DIM.EFF_DT <= 20231231 AND FNC_ST_TP_DIM.END_DT > 20231231
LEFT JOIN CG_SEG_DIM CG_SEGMENT_DIM 	ON CG_SEGMENT_DIM.CG_SEG_ID = T.CG_SEG AND CG_SEGMENT_DIM.EFF_DT <= 20231231 AND CG_SEGMENT_DIM.END_DT > 20231231
LEFT JOIN MSEG_DIM 						ON MSEG_DIM.MSEG_ID = T.MSEG AND MSEG_DIM.EFF_DT <= 20231231 AND MSEG_DIM.END_DT > 20231231
LEFT JOIN SRO_DIM 						ON SRO_DIM.SRO_CODE = T.SRO_CODE AND SRO_DIM.EFF_DT <= 20231231 AND SRO_DIM.END_DT > 20231231
LEFT JOIN PYMTC_DIM 					ON PYMTC_DIM.PYMTC_ID = T.PYMT_CARD_ID AND PYMTC_DIM.EFF_DT <= 20231231 AND PYMTC_DIM.END_DT > 20231231
--add 20220311
LEFT JOIN OU_DIM ORIG_OU ON ORIG_OU.CODE = T.RPRG_OU_CODE AND ORIG_OU.EFF_DT <= 20231231 AND ORIG_OU.END_DT > 20231231
LEFT JOIN TWT_PUB_CST_INFO ON TWT_PUB_CST_INFO.IP_ID = T.CST_ID
LEFT JOIN CST_SEG_MINI_DIM ON
	TWT_PUB_CST_INFO.LCS = CST_SEG_MINI_DIM.LCS
	AND TWT_PUB_CST_INFO.FN_ST = CST_SEG_MINI_DIM.FNC_ST_CODE
	AND TWT_PUB_CST_INFO.CLT_F = CST_SEG_MINI_DIM.CLT_F
										
UNION ALL
SELECT 
	LST.AC_AR_DIM_ID
	,LST.CST_DIM_ID
	,LST.LOAN_PPS_DIM_ID
	,LST.PD_DIM_ID
	,LST.RLTNP_OFCR_DIM_ID
	,LST.IDY_DIM_ID
	,LST.LDGR_ACG_DIM_ID
	,LST.TERM_DIM_ID
	,LST.ADJ_OU_DIM_ID
	,LST.ADJ_CCY_DIM_ID
	,LST.ADJ_LOB_DIM_ID
	,LST.CST_FNC_ST_DIM_ID
	,LST.ADJ_FNC_ST_DIM_ID
	,LST.MIS_ADJ_FNC_ST_DIM_ID
	,LST.FNL_FNC_ST_DIM_ID
	,LST.FNC_ST_TP_DIM_ID
	,LST.CG_SEG_DIM_ID
	,LST.MSEG_DIM_ID
	,0 CLS_BAL_FCY
	,0 CLS_BAL_LCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'IW')
				THEN 0
		ELSE LST.CLS_BAL_WTD_FCY END CLS_BAL_WTD_FCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'IW')
				THEN 0
		ELSE LST.CLS_BAL_WTD_LCY END CLS_BAL_WTD_LCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN 0
		ELSE LST.CLS_BAL_MTD_FCY END CLS_BAL_MTD_FCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN 0
		ELSE LST.CLS_BAL_MTD_LCY END CLS_BAL_MTD_LCY
	,0 LQD_AMT_FCY
	,0 LQD_AMT_LCY
	,0 DSBR_AMT_FCY
	,0 DSBR_AMT_LCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN 0
		ELSE LST.DSBR_AMT_MTD_LCY END DSBR_AMT_MTD_LCY
	,0 PREPYMT_AMT_FCY
	,0 PREPYMT_AMT_LCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN 0
		ELSE LST.PREPYMT_AMT_MTD_FCY END PREPYMT_AMT_MTD_FCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN 0
		ELSE LST.PREPYMT_AMT_MTD_LCY END PREPYMT_AMT_MTD_LCY
	,LST.PY_OFF_BFR_DUE_DT_F
	,LST.INT_RATE
	,LST.CDR_DT_DIM_ID
	,LST.TERM_IN_MO
	,LST.SRO_DIM_ID
	,LST.PB_MISCODE_F
	,LST.PB_CST_F
	,LST.PYMTC_DIM_ID
	,LST.MUD
	,LST.LOB_DIM_ID
	,LST.OU_DIM_ID
	,LST.CIC_FNC_ST_DIM_ID
	,LST.CCY_DIM_ID
	,LST.FNC_SVC_AR_MINI_DIM_ID
	,LST.OVRL_CST_FNC_ST_DIM_ID
	,LST.OVRL_MIS_ADJ_FNC_ST_DIM_ID
	,LST.OVRL_FNL_FNC_ST_DIM_ID
	,0 ORIG_CLS_BAL_FCY
	,0 ORIG_CLS_BAL_LCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN 0
		ELSE LST.ORIG_CLS_BAL_MTD_FCY END ORIG_CLS_BAL_MTD_FCY
	,CASE WHEN TO_DATE(20231231, 'YYYYMMDD') = TRUNC(TO_DATE(20231231, 'YYYYMMDD'), 'MONTH')
				THEN 0
		ELSE LST.ORIG_CLS_BAL_MTD_LCY END ORIG_CLS_BAL_MTD_LCY
	,LST.CMB_PD_CODE
	,LST.ORIG_PD_DIM_ID
	,LST.MIS1_OU_DIM_ID
	,LST.PD_DTL_GRP_DIM_ID
	,0 FEE_INCM_LCY
	,0 TOT_LMT_AMT
	,0 NOD_PAST_DUE
	,0 TOT_PAST_DUE_PNP
	,0 TOT_PAST_DUE_INT
	,0 CLS_UTLZ_AMT_FCY
	,0 PNP_DUE_AMT
	,0 INT_DUE_AMT
	,0 DLQ_CNT
	,0 TOT_DSBR_AMT_FCY
	,LST.AC_AR_MINI_DIM_ID
	,0 TOT_AVL_LMT_AMT
	,0 INTERIM_INT
	,LST.ORIG_OU_DIM_ID
	,LST.CST_SEG_MINI_DIM_ID
FROM FNC_SVC_AR_ANL_FCT_FA LST
JOIN AC_AR_DIM AC ON AC.AC_AR_DIM_ID = LST.AC_AR_DIM_ID
WHERE LST.CDR_DT_DIM_ID = to_number(to_char(to_date(20231231, 'yyyymmdd') - 1, 'yyyymmdd'))
	AND NOT EXISTS (
		SELECT 1
		FROM TWT_FNC_SVC_AR_ANL_FCT_FA T
		WHERE T.AC_AR_ID = AC.AC_AR_ID
		);
