SELECT 
\(9)\(9) TWT.CST_ID\(9)\(9)\(9)\(9)\(9)CST_ID
       , TWT.PD_ID\(9)\(9)\(9)\(9)\(9)PD_ID
\(9)   , PD_DIM.PD_TP\(9)\(9)\(9)\(9)PD_TP
\(9)   , TWT.ORG_UNIT_ID \(9)\(9)\(9)ORG_UNIT_ID
       , NVL(CST_DIM.CST_DIM_ID, 999999)\(9)\(9)CST_DIM_ID
       , PD_DIM.PD_DIM_ID\(9)\(9)\(9)PD_DIM_ID
       , NVL(OU_DIM.ORG_UNIT_DIM_ID, 999999)\(9)\(9)\(9)\(9)\(9)\(9)ORG_UNIT_DIM_ID
\(9)   , NVL(SLRY_TVR_SEG_DIM.SLRY_TVR_SEG_DIM_ID, 999999)\(9)\(9)\(9)SLRY_TVR_DIM_ID
       , NVL(GND_DIM.GND_DIM_ID, 999999)\(9)\(9)\(9)\(9)GND_DIM_ID
       , NVL(BRTH_AGE_SEG_DIM.AGE_SEG_DIM_ID, 0)\(9)\(9)CST_BRTH_AGE_SEG_DIM_ID
       , NVL(CST_DIM.CST_ADR, TWT.ADDR)\(9)\(9)\(9)\(9)\(9)ADDR
       , NVL(TMP_CST_SEG.OCP_DIM_ID, 999999)\(9)\(9)\(9)\(9)OCP_DIM_ID
       , NVL(TMP_CST_SEG.MAR_ST_DIM_ID, '999999')\(9)\(9)MAR_ST_DIM_ID
       , 999999\(9)\(9)\(9)\(9)\(9)CST_HIER_DIM_ID
       , NVL(TMP_CST_SEG.CST_LIFE_CYC_ST_DIM_ID, '999999')\(9)\(9)\(9)CST_LCS_TP_DIM_ID
       , NVL(TMP_CST_SEG.CST_TP_DIM_ID, 999999)\(9)\(9)\(9)\(9)\(9)\(9)CST_TP_DIM_ID
            , NVL(TMP_CST_SEG.CST_MKT_SEG_DIM_ID, 999999)\(9)\(9)CST_MKT_SEG_DIM_ID
\(9)   , NVL(NVL(CST_RLTNP_AGE_SEG.RLTNP_AGE_SEG_DIM_ID,MAX_RLTNP_AGE.RLTNP_AGE_SEG_DIM_ID) , 999999)\(9)\(9)CST_AGE_SEG_DIM_ID
       , NVL(CDR_DT_DIM.CDR_DT_DIM_ID, '999999')\(9)\(9)\(9)\(9)\(9)TM_PRD_DIM_ID
       , NVL(CST_OU_DIM.ORG_UNIT_DIM_ID, 999999)\(9)\(9)\(9)\(9)\(9)CST_ORG_UNIT_DIM_ID
       , NVL(TMP_CST_SEG.CR_RSK_RTG_DIM_ID, '999999')\(9)\(9)\(9)CR_RSK_RTG_DIM_ID
       , NVL(CR_LMT_BAL_SEG.CR_LMT_SEG_DIM_ID, 999999)\(9)\(9)\(9)\(9)CR_LMT_SEG_DIM_ID
       , NVL(TMP_CST_SEG.IDY_SML_ID_DIM_ID, '999999')\(9)\(9)\(9)\(9)IDY_SML_ID_DIM_ID
       , NVL(AST_BAL_SEG.BAL_SEG_DIM_ID, 999999)\(9)\(9)\(9)\(9)\(9)CST_AST_BAL_SEG_DIM_ID
       , NVL(LBY_BAL_SEG.BAL_SEG_DIM_ID, 999999)\(9)\(9)\(9)\(9)\(9)CST_LBY_BAL_SEG_DIM_ID
       , NVL(TMP_CST_SEG.CST_PERF_ST_DIM_ID, '999999')\(9)\(9)\(9)\(9)\(9)CST_PERF_ST_DIM_ID
       , NVL(TMP_CST_SEG.CST_OFCR_EMPE_DIM_ID,999999 )\(9)\(9)\(9)\(9)\(9)CST_RLTNP_OFCR_DIM_ID
       , NVL(SRC_STM_DIM.SRC_STM_DIM_ID, '999999')\(9)SRC_STM_DIM_ID
\(9)   
       , NBR_OF_AR_TDY
       , NBR_OF_ACTIVE_AR_TDY
       , NBR_NEW_AR_TDY
       , NBR_CLS_AR_TDY\(9)   
       , twt.TOT_AST_CLS_BAL_AMT_TDY_LCY
       , twt.TOT_LBY_CLS_BAL_AMT_TDY_LCY
       , TOT_AST_CLS_BAL_AMT_TDY_FCY
       , TOT_LBY_CLS_BAL_AMT_TDY_FCY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1 THEN NVL(PRE.TOT_AST_CLS_BAL_AMT_TDY_LCY, 0)\(9)ELSE NVL(PRE.TOT_AST_CLS_BAL_AMT_LMTH_LCY, 0)\(9)END       TOT_AST_CLS_BAL_AMT_LMTH_LCY
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1
\(9)   \(9) \(9)THEN NVL(PRE.TOT_AST_CLS_BAL_AMT_TDY_LCY, 0) ELSE NVL(PRE.TOT_AST_CLS_BAL_AMT_LQTR_LCY, 0)\(9)END     \(9)\(9)\(9)\(9)\(9)\(9)\(9)\(9)\(9)\(9)TOT_AST_CLS_BAL_AMT_LQTR_LCY
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1 THEN NVL(PRE.TOT_AST_CLS_BAL_AMT_TDY_LCY, 0) ELSE NVL(PRE.TOT_AST_CLS_BAL_AMT_LYR_LCY, 0) END    \(9)TOT_AST_CLS_BAL_AMT_LYR_LCY

\(9)          , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1 THEN NVL(PRE.TOT_LBY_CLS_BAL_AMT_TDY_LCY, 0) ELSE NVL(PRE.TOT_LBY_CLS_BAL_AMT_LMTH_LCY, 0)\(9)END     TOT_LBY_CLS_BAL_AMT_LMTH_LCY
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1
\(9)   \(9) \(9)THEN NVL(PRE.TOT_LBY_CLS_BAL_AMT_TDY_LCY, 0) ELSE NVL(PRE.TOT_LBY_CLS_BAL_AMT_LQTR_LCY, 0)\(9)END        \(9)\(9)\(9)\(9)\(9)\(9)\(9)\(9)\(9)\(9)\(9)TOT_LBY_CLS_BAL_AMT_LQTR_LCY
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1 THEN NVL(PRE.TOT_LBY_CLS_BAL_AMT_TDY_LCY, 0) ELSE NVL(PRE.TOT_LBY_CLS_BAL_AMT_LYR_LCY, 0) END\(9)     \(9)TOT_LBY_CLS_BAL_AMT_LYR_LCY


       , TWT.CST_PD_ST_CODE\(9)\(9)CST_PD_ST_CODE
       , NVL(CST_PD_ST_DIM.CST_PD_ST_DIM_ID, 999999)\(9)\(9)CST_PD_ST_DIM_ID
\(9)   , TWT.CST_PD_ST_BRN_CODE\(9)\(9)CST_PD_ST_BRN_CODE
       , NVL(CST_PD_ST_BRN_DIM.CST_PD_ST_DIM_ID, 999999)\(9)\(9)CST_PD_ST_BRN_DIM_ID\(9)

\(9)   , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)THEN NVL(TWT.NBR_NEW_AR_TDY , 0) ELSE NVL(TWT.NBR_NEW_AR_TDY , 0)+ NVL(PRE.NBR_NEW_AR_MTD, 0) END\(9)\(9)NBR_NEW_AR_MTD  
\(9)   , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)THEN NVL(TWT.NBR_CLS_AR_TDY , 0) ELSE NVL(TWT.NBR_CLS_AR_TDY , 0)+ NVL(PRE.NBR_CLS_AR_MTD, 0) END\(9)\(9)NBR_CLS_AR_MTD 
\(9)   , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.NBR_NEW_AR_TDY , 0)  ELSE NVL(TWT.NBR_NEW_AR_TDY , 0)+ NVL(PRE.NBR_NEW_AR_QTD, 0) END   \(9) NBR_NEW_AR_QTD  
\(9)   , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.NBR_CLS_AR_TDY , 0)  ELSE NVL(TWT.NBR_CLS_AR_TDY , 0)+ NVL(PRE.NBR_CLS_AR_QTD, 0) END\(9)\(9) NBR_CLS_AR_QTD 
\(9)   , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.NBR_NEW_AR_TDY , 0) ELSE NVL(TWT.NBR_NEW_AR_TDY , 0)+ NVL(PRE.NBR_NEW_AR_YTD, 0) END   NBR_NEW_AR_YTD  
\(9)   , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.NBR_CLS_AR_TDY , 0) ELSE NVL(TWT.NBR_CLS_AR_TDY , 0)+ NVL(PRE.NBR_CLS_AR_YTD, 0) END\(9)NBR_CLS_AR_YTD 
\(9)  ,  NVL(PD_USG_ST_DIM.PD_USG_ST_DIM_ID, 999999)\(9)\(9)PD_USG_ST_DIM_ID\(9)
\(9)    
\(9)\(9), NVL(TWT.TOT_FEE_INCM_AMT_TDY_LCY, 0)\(9)\(9)\(9)TOT_FEE_INCM_AMT_TDY_LCY
\(9)\(9), CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)THEN NVL(TWT.TOT_FEE_INCM_AMT_TDY_LCY, 0) ELSE  NVL(PRE.TOT_FEE_INCM_AMT_MTD_LCY, 0) + NVL(TWT.TOT_FEE_INCM_AMT_TDY_LCY, 0) END\(9)\(9)\(9)TOT_FEE_INCM_AMT_MTD_LCY
\(9)\(9), CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)      THEN NVL(TWT.TOT_FEE_INCM_AMT_TDY_LCY, 0)   ELSE NVL(TWT.TOT_FEE_INCM_AMT_TDY_LCY, 0) + NVL(PRE.TOT_FEE_INCM_AMT_QTD_LCY, 0)  END \(9)\(9)TOT_FEE_INCM_AMT_QTD_LCY
\(9)\(9), CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_FEE_INCM_AMT_TDY_LCY, 0) ELSE \(9)NVL(TWT.TOT_FEE_INCM_AMT_TDY_LCY, 0) + \(9)NVL(PRE.TOT_FEE_INCM_AMT_YTD_LCY, 0)  END \(9)\(9)TOT_FEE_INCM_AMT_YTD_LCY
\(9)\(9)\(9)\(9)\(9)
\(9)\(9), CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.NBR_OF_FNC_TXN_TDY , 0) ELSE NVL(TWT.NBR_OF_FNC_TXN_TDY , 0)+ NVL(PRE.NBR_OF_FNC_TXN_MTD, 0) END \(9)NBR_OF_FNC_TXN_MTD
\(9)\(9), CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)\(9)\(9)THEN NVL(TWT.NBR_OF_FNC_TXN_TDY , 0)  ELSE NVL(TWT.NBR_OF_FNC_TXN_TDY , 0)+ NVL(PRE.NBR_OF_FNC_TXN_QTD, 0) END \(9)NBR_OF_FNC_TXN_QTD
\(9)\(9), CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.NBR_OF_FNC_TXN_TDY , 0) ELSE NVL(TWT.NBR_OF_FNC_TXN_TDY , 0)+ NVL(PRE.NBR_OF_FNC_TXN_YTD, 0) END\(9)NBR_OF_FNC_TXN_YTD
\(9)\(9), twt.NBR_OF_FNC_TXN_TDY\(9)\(9)NBR_OF_FNC_TXN_TDY\(9)  
\(9)\(9)
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.NBR_OF_NFNC_TXN_TDY , 0) ELSE NVL(TWT.NBR_OF_NFNC_TXN_TDY , 0)+ NVL(PRE.NBR_OF_NFNC_TXN_MTD, 0) END \(9)NBR_OF_NFNC_TXN_MTD
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.NBR_OF_NFNC_TXN_TDY , 0)  ELSE NVL(TWT.NBR_OF_NFNC_TXN_TDY , 0)+ NVL(PRE.NBR_OF_NFNC_TXN_QTD, 0) END \(9)NBR_OF_NFNC_TXN_QTD
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.NBR_OF_NFNC_TXN_TDY , 0) ELSE NVL(TWT.NBR_OF_NFNC_TXN_TDY , 0)+ NVL(PRE.NBR_OF_NFNC_TXN_YTD, 0) END\(9)NBR_OF_NFNC_TXN_YTD
       , twt.NBR_OF_NFNC_TXN_TDY\(9)\(9)NBR_OF_NFNC_TXN_TDY\(9)

\(9)   
\(9), CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1 THEN NVL(TWT.TOT_NBR_OF_CST_TXN_TDY, 0)\(9)ELSE NVL(TWT.TOT_NBR_OF_CST_TXN_TDY, 0) + NVL(PRE.TOT_NBR_OF_CST_TXN_MTD, 0)\(9)END\(9)\(9)TOT_NBR_OF_CST_TXN_MTD
\(9), CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1  
\(9)\(9)THEN NVL(TWT.TOT_NBR_OF_CST_TXN_TDY, 0)\(9)ELSE NVL(TWT.TOT_NBR_OF_CST_TXN_TDY, 0) + NVL(PRE.TOT_NBR_OF_CST_TXN_QTD, 0)\(9)END\(9)\(9)TOT_NBR_OF_CST_TXN_QTD
\(9), CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1 THEN NVL(TWT.TOT_NBR_OF_CST_TXN_TDY, 0)\(9)ELSE NVL(TWT.TOT_NBR_OF_CST_TXN_TDY, 0) + NVL(PRE.TOT_NBR_OF_CST_TXN_YTD, 0)\(9)END\(9)\(9)TOT_NBR_OF_CST_TXN_YTD
\(9), NVL(TWT.TOT_NBR_OF_CST_TXN_TDY, 0)\(9)\(9)\(9)\(9)\(9)\(9)TOT_NBR_OF_CST_TXN_TDY
\(9)
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_CST_CR_AMT_TDY_LCY , 0) ELSE NVL(TWT.TOT_CST_CR_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_CST_CR_AMT_MTD_LCY, 0) END \(9)TOT_CST_CR_AMT_MTD_LCY
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_CST_CR_AMT_TDY_LCY , 0)  ELSE NVL(TWT.TOT_CST_CR_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_CST_CR_AMT_QTD_LCY, 0) END \(9)TOT_CST_CR_AMT_QTD_LCY
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_CST_CR_AMT_TDY_LCY , 0) ELSE NVL(TWT.TOT_CST_CR_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_CST_CR_AMT_YTD_LCY, 0) END\(9)TOT_CST_CR_AMT_YTD_LCY
       , twt.TOT_CST_CR_AMT_TDY_LCY\(9)\(9)TOT_CST_CR_AMT_TDY_LCY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_CST_DB_AMT_TDY_LCY , 0) ELSE NVL(TWT.TOT_CST_DB_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_CST_DB_AMT_MTD_LCY, 0) END \(9)TOT_CST_DB_AMT_MTD_LCY
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_CST_DB_AMT_TDY_LCY , 0)  ELSE NVL(TWT.TOT_CST_DB_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_CST_DB_AMT_QTD_LCY, 0) END \(9)TOT_CST_DB_AMT_QTD_LCY
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_CST_DB_AMT_TDY_LCY , 0) ELSE NVL(TWT.TOT_CST_DB_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_CST_DB_AMT_YTD_LCY, 0) END\(9)TOT_CST_DB_AMT_YTD_LCY
       , twt.TOT_CST_DB_AMT_TDY_LCY\(9)\(9)TOT_CST_DB_AMT_TDY_LCY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_OTHR_CR_AMT_TDY , 0) ELSE NVL(TWT.TOT_OTHR_CR_AMT_TDY , 0)+ NVL(PRE.TOT_OTHR_CR_AMT_MTD, 0) END \(9)TOT_OTHR_CR_AMT_MTD
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_OTHR_CR_AMT_TDY , 0)  ELSE NVL(TWT.TOT_OTHR_CR_AMT_TDY , 0)+ NVL(PRE.TOT_OTHR_CR_AMT_QTD, 0) END \(9)TOT_OTHR_CR_AMT_QTD
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_OTHR_CR_AMT_TDY , 0) ELSE NVL(TWT.TOT_OTHR_CR_AMT_TDY , 0)+ NVL(PRE.TOT_OTHR_CR_AMT_YTD, 0) END\(9)TOT_OTHR_CR_AMT_YTD
       , twt.TOT_OTHR_CR_AMT_TDY\(9)\(9)TOT_OTHR_CR_AMT_TDY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_OTHR_DB_AMT_TDY , 0) ELSE NVL(TWT.TOT_OTHR_DB_AMT_TDY , 0)+ NVL(PRE.TOT_OTHR_DB_AMT_MTD, 0) END \(9)TOT_OTHR_DB_AMT_MTD
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_OTHR_DB_AMT_TDY , 0)  ELSE NVL(TWT.TOT_OTHR_DB_AMT_TDY , 0)+ NVL(PRE.TOT_OTHR_DB_AMT_QTD, 0) END \(9)TOT_OTHR_DB_AMT_QTD
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_OTHR_DB_AMT_TDY , 0) ELSE NVL(TWT.TOT_OTHR_DB_AMT_TDY , 0)+ NVL(PRE.TOT_OTHR_DB_AMT_YTD, 0) END\(9)TOT_OTHR_DB_AMT_YTD
       , twt.TOT_OTHR_DB_AMT_TDY\(9)\(9)TOT_OTHR_DB_AMT_TDY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_NBR_OF_CST_CR_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_CST_CR_TDY , 0)+ NVL(PRE.TOT_NBR_OF_CST_CR_MTD, 0) END \(9)TOT_NBR_OF_CST_CR_MTD
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_NBR_OF_CST_CR_TDY , 0)  ELSE NVL(TWT.TOT_NBR_OF_CST_CR_TDY , 0)+ NVL(PRE.TOT_NBR_OF_CST_CR_QTD, 0) END \(9)TOT_NBR_OF_CST_CR_QTD
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_NBR_OF_CST_CR_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_CST_CR_TDY , 0)+ NVL(PRE.TOT_NBR_OF_CST_CR_YTD, 0) END\(9)TOT_NBR_OF_CST_CR_YTD
       , twt.TOT_NBR_OF_CST_CR_TDY\(9)\(9)TOT_NBR_OF_CST_CR_TDY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_NBR_OF_CST_DB_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_CST_DB_TDY , 0)+ NVL(PRE.TOT_NBR_OF_CST_DB_MTD, 0) END \(9)TOT_NBR_OF_CST_DB_MTD
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_NBR_OF_CST_DB_TDY , 0)  ELSE NVL(TWT.TOT_NBR_OF_CST_DB_TDY , 0)+ NVL(PRE.TOT_NBR_OF_CST_DB_QTD, 0) END \(9)TOT_NBR_OF_CST_DB_QTD
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_NBR_OF_CST_DB_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_CST_DB_TDY , 0)+ NVL(PRE.TOT_NBR_OF_CST_DB_YTD, 0) END\(9)TOT_NBR_OF_CST_DB_YTD
       , twt.TOT_NBR_OF_CST_DB_TDY\(9)\(9)TOT_NBR_OF_CST_DB_TDY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_NBR_OF_OTHR_CR_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_OTHR_CR_TDY , 0)+ NVL(PRE.TOT_NBR_OF_OTHR_CR_MTD, 0) END \(9)TOT_NBR_OF_OTHR_CR_MTD
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_NBR_OF_OTHR_CR_TDY , 0)  ELSE NVL(TWT.TOT_NBR_OF_OTHR_CR_TDY , 0)+ NVL(PRE.TOT_NBR_OF_OTHR_CR_QTD, 0) END \(9)TOT_NBR_OF_OTHR_CR_QTD
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_NBR_OF_OTHR_CR_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_OTHR_CR_TDY , 0)+ NVL(PRE.TOT_NBR_OF_OTHR_CR_YTD, 0) END\(9)TOT_NBR_OF_OTHR_CR_YTD
       , twt.TOT_NBR_OF_OTHR_CR_TDY\(9)\(9)TOT_NBR_OF_OTHR_CR_TDY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_NBR_OF_OTHR_DB_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_OTHR_DB_TDY , 0)+ NVL(PRE.TOT_NBR_OF_OTHR_DB_MTD, 0) END \(9)TOT_NBR_OF_OTHR_DB_MTD
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_NBR_OF_OTHR_DB_TDY , 0)  ELSE NVL(TWT.TOT_NBR_OF_OTHR_DB_TDY , 0)+ NVL(PRE.TOT_NBR_OF_OTHR_DB_QTD, 0) END \(9)TOT_NBR_OF_OTHR_DB_QTD
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_NBR_OF_OTHR_DB_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_OTHR_DB_TDY , 0)+ NVL(PRE.TOT_NBR_OF_OTHR_DB_YTD, 0) END\(9)TOT_NBR_OF_OTHR_DB_YTD
       , twt.TOT_NBR_OF_OTHR_DB_TDY\(9)\(9)TOT_NBR_OF_OTHR_DB_TDY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_ACTV_TXN_CR_AMT_TDY_LCY , 0) ELSE NVL(TWT.TOT_ACTV_TXN_CR_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_ACTV_TXN_CR_AMT_MTD_LCY, 0) END \(9)TOT_ACTV_TXN_CR_AMT_MTD_LCY
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_ACTV_TXN_CR_AMT_TDY_LCY , 0)  ELSE NVL(TWT.TOT_ACTV_TXN_CR_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_ACTV_TXN_CR_AMT_QTD_LCY, 0) END \(9)TOT_ACTV_TXN_CR_AMT_QTD_LCY
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_ACTV_TXN_CR_AMT_TDY_LCY , 0) ELSE NVL(TWT.TOT_ACTV_TXN_CR_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_ACTV_TXN_CR_AMT_YTD_LCY, 0) END\(9)TOT_ACTV_TXN_CR_AMT_YTD_LCY
       , twt.TOT_ACTV_TXN_CR_AMT_TDY_LCY\(9)\(9)TOT_ACTV_TXN_CR_AMT_TDY_LCY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_PASSIVE_TXN_CR_AMT_TDY_LCY , 0) ELSE NVL(TWT.TOT_PASSIVE_TXN_CR_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_PASSIVE_TXN_CR_AMT_MTD_LCY, 0) END \(9)TOT_PASSIVE_TXN_CR_AMT_MTD_LCY
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_PASSIVE_TXN_CR_AMT_TDY_LCY , 0)  ELSE NVL(TWT.TOT_PASSIVE_TXN_CR_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_PASSIVE_TXN_CR_AMT_QTD_LCY, 0) END \(9)TOT_PASSIVE_TXN_CR_AMT_QTD_LCY
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_PASSIVE_TXN_CR_AMT_TDY_LCY , 0) ELSE NVL(TWT.TOT_PASSIVE_TXN_CR_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_PASSIVE_TXN_CR_AMT_YTD_LCY, 0) END\(9)TOT_PASSIVE_TXN_CR_AMT_YTD_LCY
       , twt.TOT_PASSIVE_TXN_CR_AMT_TDY_LCY\(9)\(9)TOT_PASSIVE_TXN_CR_AMT_TDY_LCY\(9)   

       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_ACTV_TXN_DB_AMT_TDY_LCY , 0) ELSE NVL(TWT.TOT_ACTV_TXN_DB_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_ACTV_TXN_DB_AMT_MTD_LCY, 0) END \(9)TOT_ACTV_TXN_DB_AMT_MTD_LCY
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_ACTV_TXN_DB_AMT_TDY_LCY , 0)  ELSE NVL(TWT.TOT_ACTV_TXN_DB_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_ACTV_TXN_DB_AMT_QTD_LCY, 0) END \(9)TOT_ACTV_TXN_DB_AMT_QTD_LCY
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_ACTV_TXN_DB_AMT_TDY_LCY , 0) ELSE NVL(TWT.TOT_ACTV_TXN_DB_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_ACTV_TXN_DB_AMT_YTD_LCY, 0) END\(9)TOT_ACTV_TXN_DB_AMT_YTD_LCY
       , twt.TOT_ACTV_TXN_DB_AMT_TDY_LCY\(9)\(9)TOT_ACTV_TXN_DB_AMT_TDY_LCY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_PASSIVE_TXN_DB_AMT_TDY_LCY , 0) ELSE NVL(TWT.TOT_PASSIVE_TXN_DB_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_PASSIVE_TXN_DB_AMT_MTD_LCY, 0) END \(9)TOT_PASSIVE_TXN_DB_AMT_MTD_LCY
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_PASSIVE_TXN_DB_AMT_TDY_LCY , 0)  ELSE NVL(TWT.TOT_PASSIVE_TXN_DB_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_PASSIVE_TXN_DB_AMT_QTD_LCY, 0) END \(9)TOT_PASSIVE_TXN_DB_AMT_QTD_LCY
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_PASSIVE_TXN_DB_AMT_TDY_LCY , 0) ELSE NVL(TWT.TOT_PASSIVE_TXN_DB_AMT_TDY_LCY , 0)+ NVL(PRE.TOT_PASSIVE_TXN_DB_AMT_YTD_LCY, 0) END\(9)TOT_PASSIVE_TXN_DB_AMT_YTD_LCY
       , twt.TOT_PASSIVE_TXN_DB_AMT_TDY_LCY\(9)\(9)TOT_PASSIVE_TXN_DB_AMT_TDY_LCY\(9)
 
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_NBR_OF_ACTV_TXN_CR_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_ACTV_TXN_CR_TDY , 0)+ NVL(PRE.TOT_NBR_OF_ACTV_TXN_CR_MTD, 0) END \(9)TOT_NBR_OF_ACTV_TXN_CR_MTD
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_NBR_OF_ACTV_TXN_CR_TDY , 0)  ELSE NVL(TWT.TOT_NBR_OF_ACTV_TXN_CR_TDY , 0)+ NVL(PRE.TOT_NBR_OF_ACTV_TXN_CR_QTD, 0) END \(9)TOT_NBR_OF_ACTV_TXN_CR_QTD
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_NBR_OF_ACTV_TXN_CR_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_ACTV_TXN_CR_TDY , 0)+ NVL(PRE.TOT_NBR_OF_ACTV_TXN_CR_YTD, 0) END\(9)TOT_NBR_OF_ACTV_TXN_CR_YTD
       , twt.TOT_NBR_OF_ACTV_TXN_CR_TDY\(9)\(9)TOT_NBR_OF_ACTV_TXN_CR_TDY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_NBR_OF_PASSIVE_TXN_CR_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_PASSIVE_TXN_CR_TDY , 0)+ NVL(PRE.TOT_NBR_OF_PASSIVE_TXN_CR_MTD, 0) END \(9)TOT_NBR_OF_PASSIVE_TXN_CR_MTD
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_NBR_OF_PASSIVE_TXN_CR_TDY , 0)  ELSE NVL(TWT.TOT_NBR_OF_PASSIVE_TXN_CR_TDY , 0)+ NVL(PRE.TOT_NBR_OF_PASSIVE_TXN_CR_QTD, 0) END \(9)TOT_NBR_OF_PASSIVE_TXN_CR_QTD
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_NBR_OF_PASSIVE_TXN_CR_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_PASSIVE_TXN_CR_TDY , 0)+ NVL(PRE.TOT_NBR_OF_PASSIVE_TXN_CR_YTD, 0) END\(9)TOT_NBR_OF_PASSIVE_TXN_CR_YTD
       , twt.TOT_NBR_OF_PASSIVE_TXN_CR_TDY\(9)\(9)TOT_NBR_OF_PASSIVE_TXN_CR_TDY\(9)   

       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_NBR_OF_ACTV_TXN_DB_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_ACTV_TXN_DB_TDY , 0)+ NVL(PRE.TOT_NBR_OF_ACTV_TXN_DB_MTD, 0) END \(9)TOT_NBR_OF_ACTV_TXN_DB_MTD
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_NBR_OF_ACTV_TXN_DB_TDY , 0)  ELSE NVL(TWT.TOT_NBR_OF_ACTV_TXN_DB_TDY , 0)+ NVL(PRE.TOT_NBR_OF_ACTV_TXN_DB_QTD, 0) END \(9)TOT_NBR_OF_ACTV_TXN_DB_QTD
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_NBR_OF_ACTV_TXN_DB_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_ACTV_TXN_DB_TDY , 0)+ NVL(PRE.TOT_NBR_OF_ACTV_TXN_DB_YTD, 0) END\(9)TOT_NBR_OF_ACTV_TXN_DB_YTD
       , twt.TOT_NBR_OF_ACTV_TXN_DB_TDY\(9)\(9)TOT_NBR_OF_ACTV_TXN_DB_TDY
\(9)   
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_MO = 1\(9)then NVL(TWT.TOT_NBR_OF_PASSIVE_TXN_DB_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_PASSIVE_TXN_DB_TDY , 0)+ NVL(PRE.TOT_NBR_OF_PASSIVE_TXN_DB_MTD, 0) END \(9)TOT_NBR_OF_PASSIVE_TXN_DB_MTD
       , CASE WHEN TO_NUMBER(extract (day from TO_DATE(SYS.PARAM_VALUE,'YYYYDDD') - date_trunc('quarter', TO_DATE(SYS.PARAM_VALUE,'YYYYDDD'))),99) + 1 = 1 
\(9)     THEN NVL(TWT.TOT_NBR_OF_PASSIVE_TXN_DB_TDY , 0)  ELSE NVL(TWT.TOT_NBR_OF_PASSIVE_TXN_DB_TDY , 0)+ NVL(PRE.TOT_NBR_OF_PASSIVE_TXN_DB_QTD, 0) END \(9)TOT_NBR_OF_PASSIVE_TXN_DB_QTD
       , CASE WHEN CDR_DT_DIM.DAY_NBR_IN_CDR_YR = 1\(9)THEN NVL(TWT.TOT_NBR_OF_PASSIVE_TXN_DB_TDY , 0) ELSE NVL(TWT.TOT_NBR_OF_PASSIVE_TXN_DB_TDY , 0)+ NVL(PRE.TOT_NBR_OF_PASSIVE_TXN_DB_YTD, 0) END\(9)TOT_NBR_OF_PASSIVE_TXN_DB_YTD
       , twt.TOT_NBR_OF_PASSIVE_TXN_DB_TDY\(9)\(9)TOT_NBR_OF_PASSIVE_TXN_DB_TDY\(9)
\(9)\(9), CASE WHEN TWT.CLS_PD_IND = 1 THEN 'Y' ELSE 'N' END\(9)\(9)CLS_PD_IND   
\(9)\(9), NVL(CTY_DIM.CTY_DIM_ID,'999999')\(9)\(9)\(9)\(9)\(9)CTY_OF_RSDNC_DIM_ID
\(9)\(9), NVL(EMPE_DIM.EMPE_DIM_ID, '999999')\(9)\(9)\(9)\(9)\(9)EMPE_DIM_ID
\(9)