select
	chg.ac_ar_id,
	axr.EFF_RATE_PCT	INT_RATE
from TWT_FNC_SVC_AR_ANL_FCT_FA_CHG chg
left join ar_x_rate_tp_rltnp AXR on AXR.ar_x_rate_tp_rltnp_tp_id ='B1D1E14709EF08BBB38D361A980E4DE1'
    AND AXR.RATE_TP_ID = '2EC90B394FDFF95D4EC063F17BE70B47' 
    AND AXR.RATE_CMPT = 'INTEREST_RATE'
	and AXR.ar_id = chg.AC_AR_ID AND AXR.EFF_DT <= LAST_EFF_DT AND AXR.END_DT > LAST_EFF_DT