SELECT 
SUM( LC_AMOUNT_LCY )
FROM
TBL_BI_LC_RELEASE_SALES
WHERE
( TO_DATE( ISSUE_DATE, 'DD-MM-YYYY' ) BETWEEN : from_date AND : to_date )
AND CUSTOMER = : customerId
GROUP BY
CUSTOMER;

SELECT 
SUM( DISTINCT LOC_AMT )
FROM
STG_SEAOPS.TBL_BI_DISBURSEMENT_SALES
WHERE
CONTRACT_REF =: contract_ref
AND TRANS_TYPE IN ( '08', '09', '12' )
AND ( TO_DATE( VALUE_DATE, 'DD-MM-YYYY' ) BETWEEN : from_date AND : to_date )
GROUP BY
CONTRACT,
DAYID,
TRANS_TYPE;

SELECT 
SUM( DISTINCT CAST( AMOUNT_LCY AS DECIMAL ) )
FROM
TBL_BI_CREDIT_SALES
WHERE
( DAYID BETWEEN : from_date AND : to_date )
AND CUSTOMER_ID = : customerId  AND OUT_REFERENCE like 'TF%'
GROUP BY
CUSTOMER_ID,OUT_REFERENCE;