SELECT
	* 
FROM
	TBL_PERIOD_EVALUATION 
WHERE
	PERIOD <> 0 
	AND GROUP_CONTRACT_CONDITION NOT IN ( 'REVALUE_COLLATERAL', 'SECUR_PROP_INSURANCE' ) 
	AND ( CONTRACT_STATUS IS NULL OR CONTRACT_STATUS NOT IN ( 'OVERDUE_1', 'OVERDUE_2' ) ) 
	AND ( CONTRACT_CONDITION_STATUS IS NULL OR CONTRACT_CONDITION_STATUS <> 'STOP_FOLLOW' ) 
	AND LOCKED_KEY IS NULL 
	AND CREATE_NEXT_PERIOD_STATUS IN ( 'NEW', 'RENEW' ) 
	AND ( FORCE_CREATE_NEXT = 1 OR CAST( EVALUATION_DATE AS DATE ) < CAST( SYSDATE ) );