SELECT 
\(9)\(9)\(9)\(9)CST_ID, 
\(9)\(9)\(9)\(9)PD_ID,
\(9)\(9)\(9)\(9)NBR_NEW_AR_MTD,
\(9)\(9)\(9)\(9)NBR_NEW_AR_QTD,
\(9)\(9)\(9)\(9)NBR_NEW_AR_YTD,
\(9)\(9)\(9)\(9)NBR_CLS_AR_MTD,
\(9)\(9)\(9)\(9)NBR_CLS_AR_QTD,
\(9)\(9)\(9)\(9)NBR_CLS_AR_YTD,
\(9)\(9)\(9)\(9)TOT_FEE_INCM_AMT_MTD_LCY,
\(9)\(9)\(9)\(9)TOT_FEE_INCM_AMT_QTD_LCY,
\(9)\(9)\(9)\(9)TOT_FEE_INCM_AMT_YTD_LCY,
\(9)\(9) \(9)\(9)TOT_CST_CR_AMT_MTD_LCY
\(9)\(9)\(9)\(9), TOT_CST_CR_AMT_QTD_LCY
\(9)\(9)\(9)\(9), TOT_CST_CR_AMT_YTD_LCY
\(9)\(9)\(9)
\(9)\(9)\(9)\(9), TOT_CST_DB_AMT_MTD_LCY
\(9)\(9)\(9)\(9), TOT_CST_DB_AMT_QTD_LCY
\(9)\(9)\(9)\(9), TOT_CST_DB_AMT_YTD_LCY
\(9)\(9)\(9)
\(9)\(9)\(9)\(9), TOT_OTHR_CR_AMT_MTD
\(9)\(9)\(9)\(9), TOT_OTHR_CR_AMT_QTD
\(9)\(9)\(9)\(9), TOT_OTHR_CR_AMT_YTD
\(9)\(9)\(9)
\(9)\(9)\(9)\(9), TOT_OTHR_DB_AMT_MTD
\(9)\(9)\(9)\(9), TOT_OTHR_DB_AMT_QTD
\(9)\(9)\(9)\(9), TOT_OTHR_DB_AMT_YTD
\(9)\(9)\(9)
\(9)\(9)\(9)\(9), TOT_NBR_OF_CST_CR_MTD
\(9)\(9)\(9)\(9), TOT_NBR_OF_CST_CR_QTD
\(9)\(9)\(9)
\(9)\(9)\(9)\(9), TOT_NBR_OF_CST_CR_YTD
\(9)\(9)\(9)\(9), TOT_NBR_OF_CST_DB_MTD
\(9)\(9)\(9)\(9), TOT_NBR_OF_CST_DB_QTD
\(9)\(9)\(9)
\(9)\(9)\(9)\(9), TOT_NBR_OF_CST_DB_YTD
\(9)\(9)\(9)\(9), TOT_NBR_OF_OTHR_CR_MTD
\(9)\(9)\(9)\(9), TOT_NBR_OF_OTHR_CR_QTD
\(9)\(9)\(9)
\(9)\(9)\(9)\(9), TOT_NBR_OF_OTHR_CR_YTD
\(9)\(9)\(9)\(9), TOT_NBR_OF_OTHR_DB_MTD
\(9)\(9)\(9)\(9), TOT_NBR_OF_OTHR_DB_QTD
\(9)\(9)\(9)
\(9)\(9)\(9)\(9), TOT_NBR_OF_OTHR_DB_YTD
\(9)
\(9)\(9)\(9), NBR_OF_FNC_TXN_MTD
\(9)\(9)\(9), NBR_OF_FNC_TXN_QTD
\(9)\(9)\(9), NBR_OF_FNC_TXN_YTD
\(9)
\(9)\(9)\(9), NBR_OF_NFNC_TXN_MTD
\(9)\(9)\(9), NBR_OF_NFNC_TXN_QTD
\(9)\(9)\(9), NBR_OF_NFNC_TXN_YTD
\(9)\(9)\(9), TOT_NBR_OF_CST_TXN_MTD
\(9)\(9)\(9), TOT_NBR_OF_CST_TXN_QTD
\(9)\(9)\(9), TOT_NBR_OF_CST_TXN_YTD
\(9)\(9)\(9), TOT_ACTV_TXN_CR_AMT_MTD_LCY
\(9)\(9)\(9), TOT_ACTV_TXN_CR_AMT_QTD_LCY
\(9)\(9)\(9), TOT_ACTV_TXN_CR_AMT_YTD_LCY
\(9)\(9)\(9), TOT_ACTV_TXN_DB_AMT_MTD_LCY
\(9)\(9)\(9), TOT_ACTV_TXN_DB_AMT_QTD_LCY
\(9)\(9)\(9), TOT_ACTV_TXN_DB_AMT_YTD_LCY
\(9)\(9)\(9), TOT_PASSIVE_TXN_CR_AMT_MTD_LCY
\(9)\(9)\(9), TOT_PASSIVE_TXN_CR_AMT_QTD_LCY
\(9)\(9)\(9), TOT_PASSIVE_TXN_CR_AMT_YTD_LCY
\(9)\(9)
\(9)\(9)\(9), TOT_PASSIVE_TXN_DB_AMT_MTD_LCY
\(9)\(9)\(9), TOT_PASSIVE_TXN_DB_AMT_QTD_LCY
\(9)\(9)\(9), TOT_PASSIVE_TXN_DB_AMT_YTD_LCY
\(9)\(9)
\(9)\(9)\(9), TOT_NBR_OF_ACTV_TXN_CR_MTD
\(9)\(9)\(9), TOT_NBR_OF_ACTV_TXN_CR_QTD
\(9)\(9)\(9), TOT_NBR_OF_ACTV_TXN_CR_YTD
\(9)\(9)
\(9)\(9)\(9), TOT_NBR_OF_ACTV_TXN_DB_MTD
\(9)\(9)\(9), TOT_NBR_OF_ACTV_TXN_DB_QTD
\(9)\(9)
\(9)\(9)\(9), TOT_NBR_OF_ACTV_TXN_DB_YTD
\(9)\(9)\(9), TOT_NBR_OF_PASSIVE_TXN_CR_MTD
\(9)\(9)\(9), TOT_NBR_OF_PASSIVE_TXN_CR_QTD
\(9)\(9)\(9), TOT_NBR_OF_PASSIVE_TXN_CR_YTD
\(9)\(9)
\(9)\(9)\(9), TOT_NBR_OF_PASSIVE_TXN_DB_MTD
\(9)\(9)\(9), TOT_NBR_OF_PASSIVE_TXN_DB_QTD
\(9)\(9)\(9), TOT_NBR_OF_PASSIVE_TXN_DB_YTD\(9)\(9)\(9)
\(9)\(9)\(9), ORG_UNIT_ID
\(9)-- EDITED 10-10-2014
\(9)\(9)\(9), LAST_CST_TXN_DT_DIM_ID
\(9)\(9)\(9), TOT_AST_ACR_INT_AMT_MTD_LCY
\(9)\(9)\(9), TOT_AST_ACR_INT_AMT_QTD_LCY
\(9)\(9)\(9), TOT_AST_ACR_INT_AMT_YTD_LCY
\(9)\(9)\(9), TOT_AST_INT_PYMT_AMT_MTD_LCY
\(9)\(9)\(9), TOT_AST_INT_PYMT_AMT_QTD_LCY
\(9)\(9)\(9), TOT_AST_INT_PYMT_AMT_YTD_LCY
\(9)\(9)\(9), TOT_LBY_ACR_INT_AMT_MTD_LCY
\(9)\(9)\(9), TOT_LBY_ACR_INT_AMT_QTD_LCY
\(9)\(9)\(9), TOT_LBY_ACR_INT_AMT_YTD_LCY
\(9)\(9)\(9), TOT_AST_CLS_BAL_AMT_TDY_LCY
       \(9)\(9), TOT_LBY_CLS_BAL_AMT_TDY_LCY
\(9)\(9)\(9), TOT_AST_CLS_BAL_AMT_LMTH_LCY
\(9)\(9)\(9), TOT_AST_CLS_BAL_AMT_LQTR_LCY
\(9)\(9)\(9), TOT_AST_CLS_BAL_AMT_LYR_LCY
\(9)\(9)\(9), TOT_LBY_CLS_BAL_AMT_LMTH_LCY
\(9)\(9)\(9), TOT_LBY_CLS_BAL_AMT_LQTR_LCY
\(9)\(9)\(9), TOT_LBY_CLS_BAL_AMT_LYR_LCY
\(9)FROM CST_PD_ANL_FCT_PREDAY F
\(9)INNER JOIN SRC_STM_DIM ON SRC_STM_DIM.SRC_STM_DIM_ID = F.SRC_STM_DIM_ID AND SRC_STM_DIM.LVL_0_CODE IN ('CADENCIE_ACCT')